### ISSUE TITLE
Too much text warning

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#123]
When the allowable amount of characters is exceeded, have a more prominent message like some of the other messages that appear below the input fields. Something like the following, only better ;)

![image](https://user-images.githubusercontent.com/15659642/146465467-46f0751f-2f64-4d68-a2b0-6a02e6b077f9.png)

**Comment by steveoh** [comment]
Since the UI you are displaying is for form validation and the character count is more of a signal i don't think they should be the same.

I  made the warning larger 

![image](https://user-images.githubusercontent.com/325813/148833729-9c24b615-152f-4aba-b80d-904bc760b727.png)

There is already a warning that will show if somehow they tried to submit the form with more than the allowed characters but you won't ever see it since the textbox is limiting it on the client.

https://github.com/uic-utah/uic-inventory/blob/fcb6cdf6cf12eb1468e90c1e9a072f617cf96458/src/api/uic-inventory/src/components/FormElements/validationSchemas.js#L182

**Comment by nathankota** [comment]
Cool how it changes colors at 500 characters remaining, then gets larger at 250 remaining. This is great.
