### ISSUE TITLE
Change rejection email

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#224]
@rsparker-utah 
How should we change this? Is there a more generic contact that can replace Brianna's name and number? 

![image](https://user-images.githubusercontent.com/15659642/227638879-99d9a3e7-5f54-4a05-a8f7-9def7f6283e0.png)

**Comment by rsparker-utah** [comment]
@nathankota The workflow has a changed a bit since Brianna left. When Brianna was here, she handled all Class V inventory submissions from start to finish. Since she left, the workflow has been split up between Porter and Mark. Mark has been handling receiving the Class V inventory submissions, entering them into the UIC geodatabase (after approval), and sending out the corresponding ABR letter. Porter has been reviewing the technical details (e.g., well details) and approving the Class V inventory submissions.

This current split in duties got me thinking, do we have the option to dynamically populate the contact? For example, could the contact name and number be populated from the profile information of the web app admin user that rejected the submission? So it would look something like:

"If you have any questions please contact <**_User First name_**> <**_User Last name_**> at <**_User Phone number_**>."

I will continue to look into the option of a generic contact in case the above isn't feasible according to our roadmap/budget.

**Comment by nathankota** [comment]
I think the simpler we can make this, the better. Maybe provide the generic UIC email and let them initiate communication that way, then add Mark and Porter to the email group so they will see the incoming messages? Seems like managing communication through the email group is more sustainable in the long term than having to change the contact info in the email as positions and responsibilities within the UIC program change.
 
![image](https://user-images.githubusercontent.com/15659642/233099809-44986009-beaf-484a-b158-7ce72930e5a3.png)

**Comment by rsparker-utah** [comment]
@nathankota I spoke with Mark and Porter and we like your idea of providing the generic UIC email (uic-inventory@utah.gov) as the contact on the rejection note and managing communication through the email group. I've added both Mark and Porter to the email group to give them an idea of how this will function in practice. Thanks for the recommendation!

**Comment by steveoh** [comment]
Please validate this as I already made this change.

**Comment by nathankota** [comment]
validated
