### ISSUE TITLE
Approved inventory notification - new well added

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#255]
### I would like a 🔔 notification when a new well is added to an Approved inventory.

**Notification message:** _NK added a new well to inventory 110_ [date, time] 🔗 ✉️ 🗑️

**Comment by steveoh** [comment]
@nathankota currently, the application downgrades the status from approved to incomplete when a new well is added because the well does not have the details added to it. At what point should this notification be created and how would the user know they are then required to add the required construction details etc?

**Comment by nathankota** [comment]
> At what point should this notification be created? 

_After_ the construction details are entered.

> How would the user know they are then required to add the required construction details etc or their approved submission is now a somewhat new status of approved and incomplete?
#240 is meant to address this.

**Comment by steveoh** [comment]
Currently I think it would be difficult to impossible? to send the notification after the construction details are entered since the system updates the inventory status after every edit to an inventory - including the addition of new wells.

When a new well is created a submitted site or even an approved site becomes draft until the required data is entered it is then reset to submitted. This seems like a bug to me and we will want to be able to differentiate between submitted, approved, and approved + incomplete. Maybe it is ok for a submitted inventory to return to draft but most likely not an approved inventory. Especially since it would probably get reset back to submitted.

If we knew that an inventory was approved and then edited and set it to a new status, then we can show messages that it is no longer complete. When it becomes complete again we can then send the notification?

Something along these lines, aligning with the business process, needs to happen to be able to do this well I think.

**Comment by nathankota** [comment]
@rsparker-utah we need consider this and make sure it aligns with the rules in #143 or, more likely, change some of the rules

**Comment by nathankota** [comment]
closing for now since we are not doing post-approval editing features for public users
