### ISSUE TITLE
Site Address Dispaying as Coordinates on Inventory Review Page

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#258]
If a user selects the "skip" option on the Site Location page during site creation, then the site address displays as coordinates instead of an address on the Inventory Review Page.

Steps to recreate this are as follows:
- During site creation, user clicks the "skip" icon on the [Site Location page](https://uic-inventory.dev.utah.gov/site/98/add-location)
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/7b2490dc-7281-4533-ab90-4ca442079a59)
- User defines the site using either the "Select Parcels" or "Draw Site" tool 
- User finishes creating site
- User creates and submits an inventory for the created site.

On the resulting [Inventory Review Page](https://uic-inventory.dev.utah.gov/review/site/98/inventory/185), the Address is displayed in what appears to be units of meters for the World WGS 1984 Web Mercator (auxiliary sphere) projection:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/8525e9b3-a5d2-4462-a917-621aef755fac)

If possible, could this be adjusted to show the address for the site? 

Note: if the user inputs a valid address into the Street address and then selects/draws the parcel, then the address displays correctly in the Inventory Review Page. For example [Site ID 100](https://uic-inventory.dev.utah.gov/review/site/100/inventory/187):
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/37480627-0be5-4d31-867c-964d903f57c5)

**Comment by rsparker-utah** [comment]
This is a good point and something I had not fully considered. To answer your question, the goal in this case is to know where the site is spatially, so from that perspective the coordinates make sense. That being said, the Inventory Review export will be used for archive/reference, so would it be possible to display the coordinates in a more common format like decimal degrees?

**Comment by nathankota** [comment]
What about something similar to Atlas where, if a location is clicked when entering a site we provide an approximate street address _and_ coordinates, even if the approximate street address is `No house address found.`?

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/dd89eb1e-5c53-46bf-882a-a0e564added2)

**Comment by rsparker-utah** [comment]
Something similar to Atlas sounds reasonable. A couple of additional thoughts regarding this approach:

1. Could there be a note or notification letting the user know that if they select "skip" on the Site Location page, that the site address will be estimated?
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/f6a2508b-d70d-4ba9-a0c3-efeafd8ebdb3)

2. Assuming that an address is then estimated, is there anyway to indicate to the admin user during inventory review that the site address is an estimate?

**Comment by nathankota** [comment]
The primary goal for this workflow is to eliminate the bad addresses that were coming in through the paper forms, and to ensure we have a point to calculate what goes into the following fields if they can't enter a good (geocode-able) address:
- UICFacility.CountyFIPS
- UICFacility.FacilityCity
- UICFacility.FacilityState (not really)
- UICFacility.FacilityZip
- (and UICFacility.FacilityAddress, of course, either as an address or coordinates)

The simple changes @rsparker-utah and I determined are:
- Change "Address" to "Location" on the Inventory Review page and ABR letters
- Show the coordinates in decimal degrees on Inventory Review and ABR, when applicable (i.e. when point dropped instead of proper address added during Site creation)
